import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: 'white',
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 40,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#64748B',
    marginTop: -8,
    marginBottom: 24,
    marginLeft: 16,
    fontWeight: '500',
  },
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: 'black',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 16,
    paddingLeft: 4,
  },
  segmentControlContainer: {
    backgroundColor: '#F1F5F9',
    borderRadius: 16,
    height: 60,
    flexDirection: 'row',
    position: 'relative',
    alignItems: 'center',
  },
  segmentSlider: {
    position: 'absolute',
    height: 46,
    backgroundColor: '#FFF',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  segmentItem: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  segmentTxt: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  segmentTxtActive: {
    color: '#0F172A',
    fontWeight: '700',
  },
  textInputWrapper: {
    backgroundColor: '#F8FAFC',
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    padding: 16,
    minHeight: 140,
  },
  textInput: {
    fontSize: 16,
    color: '#0F172A',
    lineHeight: 24,
    fontWeight: '500',
    textAlignVertical: 'top',
    flex: 1,
  },
  footer: {
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  submitBtn: {
    backgroundColor: '#A0D803',
    borderRadius: 20,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#A0D803',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  submitBtnDisabled: {
    backgroundColor: '#E2E8F0',
    shadowOpacity: 0,
    elevation: 0,
  },
  submitBtnTxt: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});
