
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  scrollContent: {
    paddingBottom: 32,
    flexGrow: 1,
  },
  header: {
    fontSize: 24,
    color: "#111827",
    fontWeight: "800",
    textAlign: "center",
    marginTop: 12,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  legendRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    marginHorizontal: 16,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 24,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 6,
  },
  legendText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "600",
  },
  calendarWrap: {
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  selectedDateWrap: {
    marginHorizontal: 16,
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  selectedDateLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#065F46",
    marginRight: 8,
  },
  selectedDateText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#047857",
  },
  sectionWrap: {
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 14,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#192126",
    marginLeft: 15,
    marginTop: 15,
  },
  planSessionBtn: {
    backgroundColor: "rgba(160, 216, 3, 1)",
    marginHorizontal: 16,
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  planSessionBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  eventCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  eventDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  eventContent: {
    flex: 1,
  },
  eventType: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  eventTime: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 6,
    fontWeight: "500",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  listItem: {
    marginBottom: 14,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  arrowButton: { padding: 5 },
  arrowImage: { width: 20, height: 20, resizeMode: "contain" },
  monthText: { fontSize: 18, fontWeight: "bold", marginHorizontal: 15 },
  card: {},
  avatar: {},
  infoContainer: {},
  name: {},
  position: {},
  detailContainer: {},
  label: {},
  value: {},
  fab: {},
});
export default styles;
