import { Dimensions, StyleSheet } from "react-native";

const { width: screenWidth } = Dimensions.get("window");
const horizontalPadding = 20;
const sliderWidth = screenWidth - horizontalPadding * 2 - 16;

const styles = StyleSheet.create({
  keyboardAvoid: { flex: 1 },
  container: { flex: 1, padding: horizontalPadding, paddingBottom: 16, backgroundColor: "#F8FAFC" },
  scrollContent: { paddingBottom: 120 },
  header: { fontSize: 22, fontWeight: "700", textAlign: "center", marginBottom: 24, color: "#0f172a" },
  section: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  label: { fontSize: 14, marginBottom: 10, fontWeight: "600", color: "#334155" },
  errorText: { color: "#DC2626", fontSize: 12, marginTop: 6 },
  radioGroup: { flexDirection: "row", alignItems: "center", gap: 20 },
  radioItem: { flexDirection: "row", alignItems: "center" },
  radioIcon: { height: 22, width: 22, marginRight: 8 },
  radioText: { color: "#1e293b", fontSize: 15, fontWeight: "600" },
  datePicker: {
    borderColor: "#E2E8F0",
    padding: 14,
    borderWidth: 1,
    flexDirection: "row",
    borderRadius: 12,
    marginTop: 8,
    backgroundColor: "#fff",
    alignItems: "center",
    flex: 1,
  },
  datePickerText: { fontSize: 14, color: "#334155", flex: 1, flexShrink: 0 },
  dateTimeRow: { flexDirection: "row", gap: 12, marginTop: 8 },
  commentsInput: {
    backgroundColor: "#F1F5F9",
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
    minHeight: 120,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  commentsInputText: { fontSize: 14, color: "#1e293b", paddingVertical: 0 },
  sliderTrack: {
    width: sliderWidth,
    height: 12,
    backgroundColor: "#E2E8F0",
    borderRadius: 6,
    marginVertical: 20,
    overflow: "visible",
  },
  sliderFill: { height: 12, borderRadius: 6, position: "absolute", left: 0, top: 0 },
  sliderThumb: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#A0D803",
    position: "absolute",
    top: -10,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  sliderThumbText: { fontSize: 14, fontWeight: "800", color: "#0f172a" },
  effortLabel: { fontSize: 15, fontWeight: "600", color: "#64748B", marginTop: 12 },
  modalContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(0,0,0,0.5)" },
  calendarContainer: { backgroundColor: "#fff", padding: 20, borderRadius: 16, width: 320 },
  closeButton: { marginTop: 16, padding: 14, backgroundColor: "#A0D803", borderRadius: 12, alignItems: "center" },
  closeButtonText: { fontSize: 15, fontWeight: "600", color: "#0f172a" },
  buttView: { position: "absolute", bottom: 0, left: 0, right: 0, paddingHorizontal: 20, paddingVertical: 16, backgroundColor: "#fff", borderTopWidth: 1, borderTopColor: "#E2E8F0" },
  dropdown: {
    maxHeight: 250,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    marginTop: 4,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  dropdownItem: {
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9"
  },
  selectedDropdownItem: {
    backgroundColor: '#F7FEE7',
  },
  dropdownItemText: { fontSize: 15, color: "#334155", fontWeight: "500", flex: 1 },
  dropdownTrigger: {
    flexDirection: "row",
    height: 56,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  loader: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#F8FAFC" },
});

export default styles;
