
import { StyleSheet } from 'react-native';
 
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "white",},
  header: { fontSize: 24,color:"black", fontWeight: "700", textAlign: "center", marginTop:11  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    padding: 10,
    borderRadius: 15,
    marginVertical: 6,
    marginHorizontal:1,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 1,
  },
  avatar: { width: 50, height: 50, borderRadius: 25, marginRight: 12 },
  infoContainer: { flex: 1 },
  name: { fontSize: 12, fontWeight: "600",color:"black" },
  position: { fontSize: 12, fontWeight: "600",color:"rgba(153, 153, 153, 1)"  },
  detailContainer: { alignItems: "center", marginHorizontal: 10 },
  label: { fontSize: 12, fontWeight: "600",color:"black" },
  value: { fontSize: 12, fontWeight: "600",color:"rgba(153, 153, 153, 1)" },
  fab: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#7ED321",
    borderRadius: 30,
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 1,
  },
  contentContainer: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9",
    borderRadius: 30,
    padding: 6,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTabButton: {
    backgroundColor: "rgba(160, 216, 3, 1)",
    shadowColor: "rgba(160, 216, 3, 0.4)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  tabText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#94A3B8",
    textAlign:"center"
  },
  activeTabText: {
    color: "white",
  },
  reviewCard: {
    backgroundColor: "white",
    padding: 18,
    borderRadius: 24,
    marginVertical: 10,
    marginHorizontal: 2,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  reviewAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 14,
    borderWidth: 2,
    borderColor: "rgba(160, 216, 3, 1)",
  },
  reviewTextContainer: {
    flex: 1,
  },
  reviewSourceBadge: {
    backgroundColor: "rgba(160, 216, 3, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  reviewSourceText: {
    fontSize: 10,
    fontWeight: "800",
    color: "rgba(160, 216, 3, 1)",
    textTransform: 'uppercase',
  },
  reviewerName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1E293B",
  },
  reviewDate: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
  },
  ratingWrapper: {
    alignItems: 'flex-end',
  },
  ratingValueText: {
    fontSize: 22,
    fontWeight: "900",
    color: "rgba(160, 216, 3, 1)",
  },
  ratingMaxText: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "700",
    marginTop: -2,
  },
  progressBarContainer: {
    marginBottom: 16,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: "#F1F5F9",
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: "rgba(160, 216, 3, 1)",
    borderRadius: 3,
  },
  reviewInnerContent: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  reviewLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewLabelIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
    tintColor: "#64748B",
  },
  reviewFocusLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748B",
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  reviewFocusValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1E293B",
    lineHeight: 18,
  },
  reviewNoteBubble: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  reviewNoteValue: {
    fontSize: 13,
    color: "#475569",
    fontStyle: 'italic',
    lineHeight: 20,
    fontWeight: "500"
  },
  reviewFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  reviewBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(160, 216, 3, 0.06)",
  },
  reviewBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#0F172A",
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  // New Session Styles
  sessionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sessionTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sessionTypeIcon: {
    fontSize: 16,
    marginRight: 6,
  },
  sessionTypeLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
    textTransform: 'uppercase',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  playerInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 16,
    marginBottom: 16,
  },
  playerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  playerName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
  },
  playerSubText: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
  },
  questionnaireContainer: {
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  questionText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    lineHeight: 20,
    marginRight: 10,
  },
  scoreBadge: {
    backgroundColor: 'rgba(160, 216, 3, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(160, 216, 3, 0.2)',
  },
  scoreText: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(160, 216, 3, 1)',
  },
  answerContainer: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 8,
    marginTop: 4,
  },
  answerLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  answerText: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 18,
    fontWeight: '500',
  },
  answeredByText: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 6,
    fontStyle: 'italic',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  dateTimeText: {
    fontSize: 11,
    color: '#94A3B8',
    marginLeft: 4,
    fontWeight: '500',
  },
  // Slider Styles
  sliderContainer: {
    height: 40,
    justifyContent: 'center',
    marginTop: 8,
  },
  sliderTrackBase: {
    height: 12,
    flexDirection: 'row',
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
  },
  sliderSegment: {
    flex: 1,
  },
  sliderThumbOuter: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: 'rgba(160, 216, 3, 1)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  sliderThumbInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(160, 216, 3, 1)',
  },
  scoreValueLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  globalOverviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  globalOverviewBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E293B',
  },
  arrowIcon: {
    width: 20,
    height: 20,
    tintColor: 'rgba(160, 216, 3, 1)',
  },
});
export default styles;
