
import { StyleSheet } from 'react-native';
 
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "white",},
  header: { fontSize: 24,color:"black", fontWeight: "700", textAlign: "center", marginTop:11  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    padding: 10,
    borderRadius: 15,
    marginVertical: 6,
    marginHorizontal:1,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 1,
  },
  avatar: { width: 50, height: 50, borderRadius: 25, marginRight: 12 },
  infoContainer: { flex: 1 },
  name: { fontSize: 12, fontWeight: "600",color:"black" },
  position: { fontSize: 12, fontWeight: "600",color:"rgba(153, 153, 153, 1)"  },
  detailContainer: { alignItems: "center", marginHorizontal: 10 },
  label: { fontSize: 12, fontWeight: "600",color:"black" },
  value: { fontSize: 12, fontWeight: "600",color:"rgba(153, 153, 153, 1)" },
  fab: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#7ED321",
    borderRadius: 30,
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 1,
  },
  contentContainer: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#F1F5F9",
    borderRadius: 30,
    padding: 6,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTabButton: {
    backgroundColor: "rgba(160, 216, 3, 1)",
    shadowColor: "rgba(160, 216, 3, 0.4)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  tabText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#94A3B8",
    textAlign:"center"
  },
  activeTabText: {
    color: "white",
  },
  reviewCard: {
    backgroundColor: "white",
    padding: 18,
    borderRadius: 24,
    marginVertical: 10,
    marginHorizontal: 2,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  reviewAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 14,
    borderWidth: 2,
    borderColor: "rgba(160, 216, 3, 1)",
  },
  reviewTextContainer: {
    flex: 1,
  },
  reviewSourceBadge: {
    backgroundColor: "rgba(160, 216, 3, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 4,
  },
  reviewSourceText: {
    fontSize: 10,
    fontWeight: "800",
    color: "rgba(160, 216, 3, 1)",
    textTransform: 'uppercase',
  },
  reviewerName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1E293B",
  },
  reviewDate: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
  },
  ratingWrapper: {
    alignItems: 'flex-end',
  },
  ratingValueText: {
    fontSize: 22,
    fontWeight: "900",
    color: "rgba(160, 216, 3, 1)",
  },
  ratingMaxText: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "700",
    marginTop: -2,
  },
  progressBarContainer: {
    marginBottom: 16,
  },
  progressBarTrack: {
    height: 6,
    backgroundColor: "#F1F5F9",
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: "rgba(160, 216, 3, 1)",
    borderRadius: 3,
  },
  reviewInnerContent: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  reviewLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewLabelIcon: {
    width: 14,
    height: 14,
    marginRight: 6,
    tintColor: "#64748B",
  },
  reviewFocusLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748B",
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  reviewFocusValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1E293B",
    lineHeight: 18,
  },
  reviewNoteBubble: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  reviewNoteValue: {
    fontSize: 13,
    color: "#475569",
    fontStyle: 'italic',
    lineHeight: 20,
    fontWeight: "500"
  },
  reviewFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  reviewBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(160, 216, 3, 0.06)",
  },
  reviewBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#0F172A",
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
});
export default styles;
